AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear una instancia EC2 con un grupo de seguridad básico."

Parameters:
  ImageId:
    Type: String
    Default: ami-0e2c8caa4b6378d8c # Valor por defecto de la AMI (AMI Ubuntu)
    AllowedValues:
      - ami-0e2c8caa4b6378d8c # AMI Ubuntu
      - ami-05576a079321f21f8 # AMI Linux
    Description: ID de la AMI para lanzar la instancia.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: 'vockey'
      ImageId: !Ref ImageId # Usa el parámetro ImageId
      SecurityGroupIds:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Permitir acceso SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 20
          ToPort: 20
          CidrIp: 0.0.0.0/0