AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear una instancia EC2 con un grupo de seguridad básico."

Parameters:
  InstanceType:
    Description: "Tipo de instancia EC2"
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: "Debe ser un tipo de instancia EC2 válido."

  KeyName:
    Description: "Nombre del par de claves para acceder a la instancia por SSH."
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: "Debe ser un par de claves existente en tu cuenta de AWS."

  SSHLocation:
    Description: "El rango de IP que podrá acceder por SSH."
    Type: String
    Default: "0.0.0.0/0"
    AllowedPattern: "^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,2}$"
    ConstraintDescription: "Debe ser un rango de IP válido en formato CIDR."

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      KeyName: 'vockey'
      ImageId: ami-0c02fb55956c7d316 # AMI Amazon Linux 2 (actualiza según tu región)
      SecurityGroupIds:
        - 'default'
      Tags:
        - Key: Name
          Value: "MyEC2InstanceCreadoPorCloudFormation"