AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear una instancia EC2 sin parámetros"
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      KeyName: "vockey"
      ImageId: "ami-0e2c8caa4b6378d8c"
      SecurityGroupIds:
        - !Ref MySecurityGroup
  
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Permitir acceso SSH"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"  # Cambia esto para restringir acceso si es necesario
        - IpProtocol: "tcp"
          FromPort: 20
          ToPort: 20
          CidrIp: "0.0.0.0/0"  # Cambia esto para restringir acceso si es necesario