# . Crear una VPC con subredes en diferentes regiones usando Mappings. Se selecciona dinámicamente una zona de disponibilidad, para una región se seleccionará el rango 10.0.0.0/20 para la VPC y para la otra región 172.16.0.0/20.Añade una condición que determine si se adjunta un IGW en función de un parámetro que tomará dos valores (true, false) y por defecto tendrá true (Fn::Select y GetAZs) y se usa Fn::If para decidir si se adjunta un Internet Gateway.

AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para adma-4-2-2"

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  IGWCreated:
    Type: String
    Default: "true"
    Description: "Se crea el IGW"
    AllowedValues:
      - "true"
      - "false"

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html
Mappings: 
  VPCRegion: 
    us-east-1: 
      VPCCidrBlock: "10.0.0.0/20"
      SubnetCidrBlock: "10.0.0.0/24"
    us-west-2: 
      CidrBlock: "172.16.0.0/20"
      SubnetCidrBlock: "172.16.0.0/24"

# https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html
Conditions:
  AdjuntarIGW: !Equals
    - !Ref IGWCreated
    - "true"
      
Resources:

# https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !FindInMap [Region, !Ref "AWS::Region", VPCCidrBlock]
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: "Name"
          Value: "adma-pilados"

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html
  Subnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [Region, !Ref "AWS::Region", SubnetCidrBlock]
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
        - Key: "Name"
          Value: "adma-pilados-public-subnet"

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-internetgateway.html
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Condition: AdjuntarIGW
    Properties:
      Tags:
        - Key: "Name"
          Value: "adma-pilados-igw"

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcgatewayattachment.html
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: AdjuntarIGW
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway



  
