# Crear un Application Load Balancer (ALB) y un Auto Scaling Group en múltiples zonas de disponibilidad. Habrá un parámetro ALBPublico que me indicará si quiero mostrarlo a Internet el balanceador, y en el esquema del LoadBalancer determinaré con ¡If si es “internet-facing” o “internal”. Los nombres de los recursos serán una combinación del nombre que se escriba por parámetro y por defecto tendrá el valor “vívalalandingzone” que lo unirás usando un Join con tu propio nombre.

Parameters:
  ALBPublico:
    Type: String
    Default: "yes"
    Description: "Do you want an internet-facing load balancer?"
    AllowedValues:
      - "yes"
      - "no"

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/20
      EnableDnsSupport: true
      EnableDnsHostname: true
      Tags:
        - Key: "Name"
          Value: "adma-4-2-3-vpc"
  
  Subred1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ""
      VpcId: vpc-id
      CidrBlock: --.--.--.--/--
      Tags:
        - Key: "Name"
          Value: "adma-4-2-3-subred-1"

  Subred2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: zone-id
      VpcId: vpc-id
      CidrBlock: --.--.--.--/--
      Tags:
        - Key: "Name"
          Value: "adma-4-2-3-subred-2"

  myELBname:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - sg-id
      Subnets:
        - subnet-id
      Instances:
        - instance-id
      Listeners:
        - LoadBalancerPort: 
          InstancePort: 
          Protocol: HTTP|HTTPS|TCP|SSL
          InstanceProtocol: HTTP|HTTPS|TCP|SSL
        - LoadBalancerPort: '443'
          InstancePort: '443'
          Protocol: HTTPS
          InstanceProtocol: HTTPS
          SSLCertificateId: 
      HealthCheck:
        Target: TCP:port or HTTPS|HTTP:port/PathToPing
        HealthyThreshold: 
        Interval: 
        Timeout: 
        UnhealthyThreshold: 

  asg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs ''
      LaunchConfigurationName: 
      MaxSize: 0
      MinSize: 0
      Tags:
        - Key: "Name"
          Value: "adma-4-2-3-autoscalinggroup"
          PropagateAtLaunch: True|False
